// Auto-generated by fetch-stats.js — do not edit manually
// Last updated: 6/7/2026, 2:18:58 AM
var CRICCLUBS_STATS = {
  "lastUpdated": "2026-06-07T02:18:58.672Z",
  "lions": {
    "rankings": [],
    "batting": [],
    "bowling": [
      {
        "name": "Siddharth Chaudhary",
        "team": "Madison Lions",
        "matches": 1,
        "innings": 1,
        "overs": "3.0",
        "wickets": 2,
        "runs": 6,
        "maidens": 0,
        "bestFigures": "2/6",
        "hattricks": 0,
        "fourWickets": 0,
        "fiveWickets": 0,
        "wides": 3,
        "noballs": 0,
        "average": 3,
        "economy": 2,
        "strikeRate": 9,
        "leagueBowlRank": null
      }
    ],
    "batting2025": [],
    "bowling2025": [],
    "bowlingGames": []
  },
  "tigers": {
    "rankings": [],
    "batting": [],
    "bowling": [],
    "batting2025": [],
    "bowling2025": [],
    "bowlingGames": []
  },
  "combined": {
    "rankings": []
  },
  "opponents": {
    "0": {
      "batting": [],
      "bowling": [
        {
          "name": "CCCarnivals Cricket Club",
          "team": "0",
          "matches": 0,
          "innings": 0,
          "overs": "0",
          "wickets": 0,
          "runs": 0,
          "maidens": 0,
          "bestFigures": "0.00",
          "hattricks": 0,
          "fourWickets": 0,
          "fiveWickets": 0,
          "wides": 0,
          "noballs": 0,
          "average": null,
          "economy": null,
          "strikeRate": null
        },
        {
          "name": "FGFSC Gladiators",
          "team": "0",
          "matches": 0,
          "innings": 0,
          "overs": "0",
          "wickets": 0,
          "runs": 0,
          "maidens": 0,
          "bestFigures": "0.00",
          "hattricks": 0,
          "fourWickets": 0,
          "fiveWickets": 0,
          "wides": 0,
          "noballs": 0,
          "average": null,
          "economy": null,
          "strikeRate": null
        },
        {
          "name": "NCNCA",
          "team": "0",
          "matches": 0,
          "innings": 0,
          "overs": "0",
          "wickets": 0,
          "runs": 0,
          "maidens": 0,
          "bestFigures": "0.00",
          "hattricks": 0,
          "fourWickets": 0,
          "fiveWickets": 0,
          "wides": 0,
          "noballs": 0,
          "average": null,
          "economy": null,
          "strikeRate": null
        }
      ]
    },
    "1": {
      "batting": [],
      "bowling": [
        {
          "name": "Predators",
          "team": "1",
          "matches": 1,
          "innings": 0,
          "overs": "0",
          "wickets": 0,
          "runs": 2,
          "maidens": 0,
          "bestFigures": "6.25",
          "hattricks": 0,
          "fourWickets": 0,
          "fiveWickets": 0,
          "wides": 0,
          "noballs": 0,
          "average": null,
          "economy": null,
          "strikeRate": null
        },
        {
          "name": "MTMadison Tigers",
          "team": "1",
          "matches": 1,
          "innings": 0,
          "overs": "0",
          "wickets": 0,
          "runs": 2,
          "maidens": 0,
          "bestFigures": "1.89",
          "hattricks": 0,
          "fourWickets": 0,
          "fiveWickets": 0,
          "wides": 0,
          "noballs": 0,
          "average": null,
          "economy": null,
          "strikeRate": null
        },
        {
          "name": "DCDragons Cricket Club",
          "team": "1",
          "matches": 0,
          "innings": 1,
          "overs": "0",
          "wickets": 0,
          "runs": 0,
          "maidens": 0,
          "bestFigures": "-1.89",
          "hattricks": 0,
          "fourWickets": 0,
          "fiveWickets": 0,
          "wides": 0,
          "noballs": 0,
          "average": null,
          "economy": null,
          "strikeRate": null
        },
        {
          "name": "LLLascassas Lions",
          "team": "1",
          "matches": 0,
          "innings": 1,
          "overs": "0",
          "wickets": 0,
          "runs": 0,
          "maidens": 0,
          "bestFigures": "-6.25",
          "hattricks": 0,
          "fourWickets": 0,
          "fiveWickets": 0,
          "wides": 0,
          "noballs": 0,
          "average": null,
          "economy": null,
          "strikeRate": null
        }
      ]
    }
  },
  "opponents2025": {
    "0": {
      "batting": [],
      "bowling": []
    },
    "1": {
      "batting": [],
      "bowling": []
    }
  },
  "standings": [
    {
      "team": "Predators",
      "matches": 1,
      "won": 1,
      "lost": 0,
      "noResult": 0,
      "tied": 2,
      "points": 0,
      "nrr": 0
    },
    {
      "team": "MTMadison Tigers",
      "matches": 1,
      "won": 1,
      "lost": 0,
      "noResult": 0,
      "tied": 2,
      "points": 0,
      "nrr": 0
    },
    {
      "team": "DCDragons Cricket Club",
      "matches": 1,
      "won": 0,
      "lost": 1,
      "noResult": 0,
      "tied": 0,
      "points": 0,
      "nrr": 0
    },
    {
      "team": "LLLascassas Lions",
      "matches": 1,
      "won": 0,
      "lost": 1,
      "noResult": 0,
      "tied": 0,
      "points": 0,
      "nrr": 0
    },
    {
      "team": "CCCarnivals Cricket Club",
      "matches": 0,
      "won": 0,
      "lost": 0,
      "noResult": 0,
      "tied": 0,
      "points": 0,
      "nrr": 0
    },
    {
      "team": "FGFSC Gladiators",
      "matches": 0,
      "won": 0,
      "lost": 0,
      "noResult": 0,
      "tied": 0,
      "points": 0,
      "nrr": 0
    },
    {
      "team": "NCNCA",
      "matches": 0,
      "won": 0,
      "lost": 0,
      "noResult": 0,
      "tied": 0,
      "points": 0,
      "nrr": 0
    }
  ],
  "standings2025": [],
  "results": {}
};
