// Auto-generated by fetch-leather-stats.js — do not edit manually
// Last updated: 2026-07-19T13:36:38.305Z
var LEATHER_STATS = {
  "lastUpdated": "2026-07-19T13:36:38.305Z",
  "t30_2026": {
    "leagueId": "21",
    "leather": {
      "batting": [],
      "bowling": [],
      "bowlingGames": []
    },
    "opponents": {},
    "standings": [],
    "results": {}
  },
  "t20_2025": {
    "batting": [],
    "bowling": []
  },
  "t20_2024": {
    "batting": [],
    "bowling": []
  }
};