// Auto-generated by scraper/fetch-toss.js — do not edit manually
// Contains toss results for all 2026 Tape 20 league matches
var TOSS_DATA = [
  {
    "matchId": "1799",
    "date": "2026-05-03",
    "team1": "Madison Tigers",
    "team2": "Rockvale Risers",
    "resultText": null,
    "tossWinner": "Madison Tigers",
    "electedTo": "bat",
    "tossText": "Madison Tigers won the toss and elected to bat"
  },
  {
    "matchId": "1798",
    "date": "2026-05-03",
    "team1": "Mumbai Risers",
    "team2": "Franklin Falcons",
    "resultText": null,
    "tossWinner": "Mumbai Risers",
    "electedTo": "bat",
    "tossText": "Mumbai Risers won the toss and elected to bat"
  },
  {
    "matchId": "1797",
    "date": "2026-05-03",
    "team1": "Star Strikers",
    "team2": "Shoals Strikers",
    "resultText": null,
    "tossWinner": "Star Strikers",
    "electedTo": "bat",
    "tossText": "Star Strikers won the toss and elected to bat"
  },
  {
    "matchId": "1796",
    "date": "2026-05-03",
    "team1": "Madison Lions",
    "team2": "Cool Springs Titans",
    "resultText": null,
    "tossWinner": "Madison Lions",
    "electedTo": "bat",
    "tossText": "Madison Lions won the toss and elected to bat"
  },
  {
    "matchId": "1792",
    "date": "2026-05-03",
    "team1": "Game Swingers",
    "team2": "Afghan Eagles",
    "resultText": null,
    "tossWinner": "Game Swingers",
    "electedTo": "bat",
    "tossText": "Game Swingers won the toss and elected to bat"
  },
  {
    "matchId": "1791",
    "date": "2026-05-03",
    "team1": "Fearless Raiders",
    "team2": "Fearless Fighters",
    "resultText": null,
    "tossWinner": "Fearless Raiders",
    "electedTo": "bat",
    "tossText": "Fearless Raiders won the toss and elected to bat"
  },
  {
    "matchId": "1785",
    "date": "04/26/2026",
    "team1": "FSC Raptors",
    "team2": "Rockvale Risers",
    "resultText": null,
    "tossWinner": null,
    "electedTo": null,
    "tossText": null
  },
  {
    "matchId": "1784",
    "date": "04/26/2026",
    "team1": "Game Swingers",
    "team2": "Shoals Strikers",
    "resultText": null,
    "tossWinner": "Game Swingers",
    "electedTo": "bat",
    "tossText": "Game Swingers won the toss and elected to bat"
  },
  {
    "matchId": "1783",
    "date": "04/26/2026",
    "team1": "Madison Tigers",
    "team2": "Afghan Eagles",
    "resultText": null,
    "tossWinner": "Madison Tigers",
    "electedTo": "bat",
    "tossText": "Madison Tigers won the toss and elected to bat"
  },
  {
    "matchId": "1782",
    "date": "04/26/2026",
    "team1": "Fearless Fighters",
    "team2": "Mumbai Risers",
    "resultText": null,
    "tossWinner": "Fearless Fighters",
    "electedTo": "bat",
    "tossText": "Fearless Fighters won the toss and elected to bat"
  },
  {
    "matchId": "1777",
    "date": "04/26/2026",
    "team1": "Nashville Underdogs",
    "team2": "Cool Springs Titans",
    "resultText": null,
    "tossWinner": "Cool Springs Titans",
    "electedTo": "field",
    "tossText": "Cool Springs Titans won the toss and elected to bowl"
  },
  {
    "matchId": "1776",
    "date": "04/26/2026",
    "team1": "Fearless Raiders",
    "team2": "Great Marathas",
    "resultText": null,
    "tossWinner": "Fearless Raiders",
    "electedTo": "bat",
    "tossText": "Fearless Raiders won the toss and elected to bat"
  },
  {
    "matchId": "1770",
    "date": "04/19/2026",
    "team1": "Franklin Falcons",
    "team2": "Shoals Strikers",
    "resultText": null,
    "tossWinner": "Franklin Falcons",
    "electedTo": "bat",
    "tossText": "Franklin Falcons won the toss and elected to bat"
  },
  {
    "matchId": "1769",
    "date": "04/19/2026",
    "team1": "Game Swingers",
    "team2": "Mumbai Risers",
    "resultText": null,
    "tossWinner": "Game Swingers",
    "electedTo": "bat",
    "tossText": "Game Swingers won the toss and elected to bat"
  },
  {
    "matchId": "1768",
    "date": "04/19/2026",
    "team1": "Madison Tigers",
    "team2": "Fearless Fighters",
    "resultText": null,
    "tossWinner": "Madison Tigers",
    "electedTo": "bat",
    "tossText": "Madison Tigers won the toss and elected to bat"
  },
  {
    "matchId": "1767",
    "date": "04/19/2026",
    "team1": "Great Marathas",
    "team2": "Rockvale Risers",
    "resultText": null,
    "tossWinner": "Great Marathas",
    "electedTo": "bat",
    "tossText": "Great Marathas won the toss and elected to bat"
  },
  {
    "matchId": "1763",
    "date": "04/19/2026",
    "team1": "Fearless Raiders",
    "team2": "Afghan Eagles",
    "resultText": null,
    "tossWinner": "Fearless Raiders",
    "electedTo": "bat",
    "tossText": "Fearless Raiders won the toss and elected to bat"
  },
  {
    "matchId": "1762",
    "date": "04/19/2026",
    "team1": "Cool Springs Titans",
    "team2": "FSC Raptors",
    "resultText": null,
    "tossWinner": "FSC Raptors",
    "electedTo": "field",
    "tossText": "FSC Raptors won the toss and elected to bowl"
  },
  {
    "matchId": "1771",
    "date": "04/12/2026",
    "team1": "Fearless Fighters",
    "team2": "Madison Lions",
    "resultText": null,
    "tossWinner": null,
    "electedTo": null,
    "tossText": null
  },
  {
    "matchId": "1756",
    "date": "04/12/2026",
    "team1": "Afghan Eagles",
    "team2": "Mumbai Risers",
    "resultText": null,
    "tossWinner": "Afghan Eagles",
    "electedTo": "bat",
    "tossText": "Afghan Eagles won the toss and elected to bat"
  },
  {
    "matchId": "1755",
    "date": "04/12/2026",
    "team1": "Madison Tigers",
    "team2": "Great Marathas",
    "resultText": null,
    "tossWinner": "Madison Tigers",
    "electedTo": "bat",
    "tossText": "Madison Tigers won the toss and elected to bat"
  },
  {
    "matchId": "1754",
    "date": "04/12/2026",
    "team1": "MCA",
    "team2": "Shoals Strikers",
    "resultText": null,
    "tossWinner": "MCA",
    "electedTo": "bat",
    "tossText": "MCA won the toss and elected to bat"
  },
  {
    "matchId": "1753",
    "date": "04/12/2026",
    "team1": "Franklin Falcons",
    "team2": "Nashville Underdogs",
    "resultText": null,
    "tossWinner": "Franklin Falcons",
    "electedTo": "bat",
    "tossText": "Franklin Falcons won the toss and elected to bat"
  },
  {
    "matchId": "1748",
    "date": "04/12/2026",
    "team1": "Fearless Raiders",
    "team2": "Rockvale Risers",
    "resultText": null,
    "tossWinner": "Rockvale Risers",
    "electedTo": "field",
    "tossText": "Rockvale Risers won the toss and elected to bowl"
  },
  {
    "matchId": "1742",
    "date": "04/05/2026",
    "team1": "Madison Lions",
    "team2": "Rockvale Risers",
    "resultText": null,
    "tossWinner": "Madison Lions",
    "electedTo": "bat",
    "tossText": "Madison Lions won the toss and elected to bat"
  },
  {
    "matchId": "1741",
    "date": "04/05/2026",
    "team1": "MCA",
    "team2": "Cool Springs Titans",
    "resultText": null,
    "tossWinner": "MCA",
    "electedTo": "bat",
    "tossText": "MCA won the toss and elected to bat"
  },
  {
    "matchId": "1740",
    "date": "04/05/2026",
    "team1": "Great Marathas",
    "team2": "Nashville Underdogs",
    "resultText": null,
    "tossWinner": "Great Marathas",
    "electedTo": "bat",
    "tossText": "Great Marathas won the toss and elected to bat"
  },
  {
    "matchId": "1739",
    "date": "04/05/2026",
    "team1": "Afghan Eagles",
    "team2": "Fearless Fighters",
    "resultText": null,
    "tossWinner": "Afghan Eagles",
    "electedTo": "bat",
    "tossText": "Afghan Eagles won the toss and elected to bat"
  },
  {
    "matchId": "1735",
    "date": "04/05/2026",
    "team1": "Star Strikers",
    "team2": "Fearless Raiders",
    "resultText": null,
    "tossWinner": "Fearless Raiders",
    "electedTo": "field",
    "tossText": "Fearless Raiders won the toss and elected to bowl"
  },
  {
    "matchId": "1734",
    "date": "04/05/2026",
    "team1": "FSC Raptors",
    "team2": "Madison Tigers",
    "resultText": null,
    "tossWinner": "FSC Raptors",
    "electedTo": "bat",
    "tossText": "FSC Raptors won the toss and elected to bat"
  },
  {
    "matchId": "1728",
    "date": "03/29/2026",
    "team1": "Mumbai Risers",
    "team2": "Shoals Strikers",
    "resultText": null,
    "tossWinner": "Mumbai Risers",
    "electedTo": "bat",
    "tossText": "Mumbai Risers won the toss and elected to bat"
  },
  {
    "matchId": "1727",
    "date": "03/29/2026",
    "team1": "Madison Lions",
    "team2": "Nashville Underdogs",
    "resultText": null,
    "tossWinner": "Madison Lions",
    "electedTo": "bat",
    "tossText": "Madison Lions won the toss and elected to bat"
  },
  {
    "matchId": "1723",
    "date": "03/29/2026",
    "team1": "Fearless Fighters",
    "team2": "Rockvale Risers",
    "resultText": null,
    "tossWinner": "Fearless Fighters",
    "electedTo": "bat",
    "tossText": "Fearless Fighters won the toss and elected to bat"
  },
  {
    "matchId": "1722",
    "date": "03/29/2026",
    "team1": "Franklin Falcons",
    "team2": "Cool Springs Titans",
    "resultText": null,
    "tossWinner": "Franklin Falcons",
    "electedTo": "bat",
    "tossText": "Franklin Falcons won the toss and elected to bat"
  },
  {
    "matchId": "1716",
    "date": "03/22/2026",
    "team1": "Madison Tigers",
    "team2": "Franklin Falcons",
    "resultText": null,
    "tossWinner": "Madison Tigers",
    "electedTo": "bat",
    "tossText": "Madison Tigers won the toss and elected to bat"
  },
  {
    "matchId": "1715",
    "date": "03/22/2026",
    "team1": "Cool Springs Titans",
    "team2": "Great Marathas",
    "resultText": null,
    "tossWinner": "Cool Springs Titans",
    "electedTo": "bat",
    "tossText": "Cool Springs Titans won the toss and elected to bat"
  },
  {
    "matchId": "1710",
    "date": "03/22/2026",
    "team1": "Nashville Underdogs",
    "team2": "Star Strikers",
    "resultText": null,
    "tossWinner": "Star Strikers",
    "electedTo": "field",
    "tossText": "Star Strikers won the toss and elected to bowl"
  },
  {
    "matchId": "1709",
    "date": "03/22/2026",
    "team1": "FSC Raptors",
    "team2": "Afghan Eagles",
    "resultText": null,
    "tossWinner": "Afghan Eagles",
    "electedTo": "field",
    "tossText": "Afghan Eagles won the toss and elected to bowl"
  },
  {
    "matchId": "1704",
    "date": "03/15/2026",
    "team1": "Franklin Falcons",
    "team2": "Game Swingers",
    "resultText": null,
    "tossWinner": "Franklin Falcons",
    "electedTo": "bat",
    "tossText": "Franklin Falcons won the toss and elected to bat"
  },
  {
    "matchId": "1703",
    "date": "03/15/2026",
    "team1": "Great Marathas",
    "team2": "Madison Lions",
    "resultText": null,
    "tossWinner": "Great Marathas",
    "electedTo": "bat",
    "tossText": "Great Marathas won the toss and elected to bat"
  },
  {
    "matchId": "1698",
    "date": "03/15/2026",
    "team1": "FSC Raptors",
    "team2": "Mumbai Risers",
    "resultText": null,
    "tossWinner": "FSC Raptors",
    "electedTo": "bat",
    "tossText": "FSC Raptors won the toss and elected to bat"
  },
  {
    "matchId": "1697",
    "date": "03/15/2026",
    "team1": "Fearless Raiders",
    "team2": "MCA",
    "resultText": null,
    "tossWinner": "Fearless Raiders",
    "electedTo": "bat",
    "tossText": "Fearless Raiders won the toss and elected to bat"
  },
  {
    "matchId": "1692",
    "date": "03/08/2026",
    "team1": "Game Swingers",
    "team2": "Cool Springs Titans",
    "resultText": null,
    "tossWinner": null,
    "electedTo": null,
    "tossText": null
  },
  {
    "matchId": "1691",
    "date": "03/08/2026",
    "team1": "Star Strikers",
    "team2": "MCA",
    "resultText": null,
    "tossWinner": null,
    "electedTo": null,
    "tossText": null
  },
  {
    "matchId": "1686",
    "date": "03/07/2026",
    "team1": "Rockvale Risers",
    "team2": "Nashville Underdogs",
    "resultText": null,
    "tossWinner": "Rockvale Risers",
    "electedTo": "bat",
    "tossText": "Rockvale Risers won the toss and elected to bat"
  },
  {
    "matchId": "1681",
    "date": "03/07/2026",
    "team1": "Fearless Raiders",
    "team2": "FSC Raptors",
    "resultText": null,
    "tossWinner": "Fearless Raiders",
    "electedTo": "bat",
    "tossText": "Fearless Raiders won the toss and elected to bat"
  },
  {
    "matchId": "1680",
    "date": "03/01/2026",
    "team1": "Game Swingers",
    "team2": "Fearless Fighters",
    "resultText": null,
    "tossWinner": "Game Swingers",
    "electedTo": "bat",
    "tossText": "Game Swingers won the toss and elected to bat"
  },
  {
    "matchId": "1675",
    "date": "03/01/2026",
    "team1": "FSC Raptors",
    "team2": "Madison Lions",
    "resultText": null,
    "tossWinner": "FSC",
    "electedTo": "bat",
    "tossText": "FSC won the toss and elected to bat"
  },
  {
    "matchId": "1674",
    "date": "02/28/2026",
    "team1": "Mumbai Risers",
    "team2": "MCA",
    "resultText": null,
    "tossWinner": "Mumbai Risers",
    "electedTo": "bat",
    "tossText": "Mumbai Risers won the toss and elected to bat"
  },
  {
    "matchId": "1669",
    "date": "02/28/2026",
    "team1": "Star Strikers",
    "team2": "Madison Tigers",
    "resultText": null,
    "tossWinner": "Madison Tigers",
    "electedTo": "field",
    "tossText": "Madison Tigers won the toss and elected to bowl"
  }
];
